// Generated by scripts/generate-flock-catalog.py. Do not edit.
#ifndef CYPHER_FLOCK_SIGNATURE_CATALOG_H
#define CYPHER_FLOCK_SIGNATURE_CATALOG_H

#include <stddef.h>
#include <stdint.h>

namespace FlockCatalog {
static const char VERSION[] = "2026.07.08.1";
static const char HASH[] = "c445fbc359b1";
enum EvidenceTier : uint8_t { kCandidate = 1, kMedium = 2, kHigh = 3 };
struct OuiSignature { const char *id; uint8_t bytes[3]; EvidenceTier evidence; bool standalone; };
struct NameSignature { const char *id; const char *value; bool prefix; EvidenceTier evidence; };
struct ManufacturerSignature { const char *id; uint16_t value; EvidenceTier evidence; bool standalone; };
struct UuidSignature { const char *id; const char *value; };

static const OuiSignature WIFI_OUIS[] = {
  {"wifi.oui.flock_owned", {0xb4, 0x1e, 0x52}, (EvidenceTier)3, true},
  {"wifi.oui.field_local", {0x82, 0x6b, 0xf2}, (EvidenceTier)2, false},
  {"wifi.oui.liteon.70c94e", {0x70, 0xc9, 0x4e}, (EvidenceTier)2, false},
  {"wifi.oui.liteon.3c9180", {0x3c, 0x91, 0x80}, (EvidenceTier)2, false},
  {"wifi.oui.liteon.d8f3bc", {0xd8, 0xf3, 0xbc}, (EvidenceTier)2, false},
  {"wifi.oui.liteon.803049", {0x80, 0x30, 0x49}, (EvidenceTier)2, false},
  {"wifi.oui.liteon.145afc", {0x14, 0x5a, 0xfc}, (EvidenceTier)2, false},
  {"wifi.oui.liteon.744ca1", {0x74, 0x4c, 0xa1}, (EvidenceTier)2, false},
  {"wifi.oui.ugsi.083a88", {0x08, 0x3a, 0x88}, (EvidenceTier)2, false},
  {"wifi.oui.liteon.9c2f9d", {0x9c, 0x2f, 0x9d}, (EvidenceTier)2, false},
  {"wifi.oui.liteon.c03532", {0xc0, 0x35, 0x32}, (EvidenceTier)2, false},
  {"wifi.oui.liteon.940853", {0x94, 0x08, 0x53}, (EvidenceTier)2, false},
  {"wifi.oui.liteon.e4aaea", {0xe4, 0xaa, 0xea}, (EvidenceTier)2, false},
  {"wifi.oui.liteon.f46add", {0xf4, 0x6a, 0xdd}, (EvidenceTier)2, false},
  {"wifi.oui.liteon.24b2b9", {0x24, 0xb2, 0xb9}, (EvidenceTier)2, false},
  {"wifi.oui.liteon.00f48d", {0x00, 0xf4, 0x8d}, (EvidenceTier)2, false},
  {"wifi.oui.liteon.d03957", {0xd0, 0x39, 0x57}, (EvidenceTier)2, false},
  {"wifi.oui.liteon.e8d0fc", {0xe8, 0xd0, 0xfc}, (EvidenceTier)2, false},
  {"wifi.oui.ugsi.e04f43", {0xe0, 0x4f, 0x43}, (EvidenceTier)2, false},
  {"wifi.oui.liteon.b81ea4", {0xb8, 0x1e, 0xa4}, (EvidenceTier)2, false},
  {"wifi.oui.liteon.700894", {0x70, 0x08, 0x94}, (EvidenceTier)1, false},
  {"wifi.oui.silabs.588e81", {0x58, 0x8e, 0x81}, (EvidenceTier)2, false},
  {"wifi.oui.silabs.ec1bbd", {0xec, 0x1b, 0xbd}, (EvidenceTier)2, false},
  {"wifi.oui.espressif.3c71bf", {0x3c, 0x71, 0xbf}, (EvidenceTier)1, false},
  {"wifi.oui.liteon.5800e3", {0x58, 0x00, 0xe3}, (EvidenceTier)1, false},
  {"wifi.oui.silabs.9035ea", {0x90, 0x35, 0xea}, (EvidenceTier)2, false},
  {"wifi.oui.liteon.5c93a2", {0x5c, 0x93, 0xa2}, (EvidenceTier)1, false},
  {"wifi.oui.liteon.646e69", {0x64, 0x6e, 0x69}, (EvidenceTier)1, false},
  {"wifi.oui.samsung.4827ea", {0x48, 0x27, 0xea}, (EvidenceTier)1, false},
  {"wifi.oui.espressif.a4cf12", {0xa4, 0xcf, 0x12}, (EvidenceTier)1, false},
  {"wifi.oui.silabs.040d84", {0x04, 0x0d, 0x84}, (EvidenceTier)2, false},
  {"wifi.oui.silabs.f082c0", {0xf0, 0x82, 0xc0}, (EvidenceTier)2, false},
  {"wifi.oui.silabs.1c34f1", {0x1c, 0x34, 0xf1}, (EvidenceTier)2, false},
  {"wifi.oui.silabs.385b44", {0x38, 0x5b, 0x44}, (EvidenceTier)2, false},
  {"wifi.oui.silabs.943469", {0x94, 0x34, 0x69}, (EvidenceTier)2, false},
  {"wifi.oui.silabs.b4e3f9", {0xb4, 0xe3, 0xf9}, (EvidenceTier)2, false},
};
static const size_t WIFI_OUI_COUNT = sizeof(WIFI_OUIS) / sizeof(WIFI_OUIS[0]);

static const NameSignature BLE_NAMES[] = {
  {"ble.name.battery", "FS Ext Battery", false, (EvidenceTier)2},
  {"ble.name.flockcam", "FlockCam", true, (EvidenceTier)1},
  {"ble.name.pigvision", "Pigvision", true, (EvidenceTier)2},
};
static const size_t BLE_NAME_COUNT = sizeof(BLE_NAMES) / sizeof(BLE_NAMES[0]);

static const ManufacturerSignature BLE_MANUFACTURERS[] = {
  {"ble.company.xuntong", 2504, (EvidenceTier)1, false},
};
static const size_t BLE_MANUFACTURER_COUNT = sizeof(BLE_MANUFACTURERS) / sizeof(BLE_MANUFACTURERS[0]);

static const UuidSignature RAVEN_CUSTOM_UUIDS[] = {
  {"ble.raven.gps", "00003100-0000-1000-8000-00805f9b34fb"},
  {"ble.raven.power", "00003200-0000-1000-8000-00805f9b34fb"},
  {"ble.raven.network", "00003300-0000-1000-8000-00805f9b34fb"},
  {"ble.raven.upload", "00003400-0000-1000-8000-00805f9b34fb"},
  {"ble.raven.error", "00003500-0000-1000-8000-00805f9b34fb"},
};
static const size_t RAVEN_CUSTOM_UUID_COUNT = sizeof(RAVEN_CUSTOM_UUIDS) / sizeof(RAVEN_CUSTOM_UUIDS[0]);

static const UuidSignature RAVEN_CONTEXT_UUIDS[] = {
  {"ble.context.device_info", "0000180a-0000-1000-8000-00805f9b34fb"},
  {"ble.context.health", "00001809-0000-1000-8000-00805f9b34fb"},
  {"ble.context.location", "00001819-0000-1000-8000-00805f9b34fb"},
};
static const size_t RAVEN_CONTEXT_UUID_COUNT = sizeof(RAVEN_CONTEXT_UUIDS) / sizeof(RAVEN_CONTEXT_UUIDS[0]);
}  // namespace FlockCatalog

#endif
