#!/usr/bin/env python3
"""Turn the raw cypher-mpc-kit samples into the MPC's built-in kit.

Reads the float32 mono 22050 Hz decodes (ffmpeg output), conditions each hit,
and emits both an SD-card-ready WAV set and the C source that ships the kit in
flash. Processing happens in float and quantizes to int16 only at the end, so
the very quiet snares (peak 0.063) do not inherit amplified quantization noise.
"""
import struct, os, math

RATE = 22050
MAX_SEC = 2.0
MAX_FRAMES = int(RATE * MAX_SEC)
TARGET_PEAK = 0.891           # -1 dBFS, leaves mixer headroom
FADE_IN_MS = 1.0              # kills the click at a hard sample start
FADE_OUT_NATURAL_MS = 5.0
FADE_OUT_TRUNCATED_MS = 40.0  # a crash cut at 2 s would otherwise pop
SILENCE_FLOOR = 0.004         # trim threshold, relative to peak

# pad index -> (source stem, label, default velocity, choke group, gain)
# Bottom row (pads 1-4) is the core groove because pad 1 is bottom-left.
# Every hi-hat shares choke group 1: one physical hat can only make one sound.
KIT = [
    ("kick22",                 "Kick",      118, 0, 255),
    ("snare-bottom-buttend1",  "Snare",     112, 0, 240),
    ("chh4",                   "CHat",       92, 1, 155),
    ("hohh9",                  "OpenHat",    96, 1, 170),

    ("snare-bottom-buttend2",  "Snare2",    108, 0, 230),
    ("rimshot16",              "Rim",       104, 0, 200),
    ("sidestick14",            "Stick",      98, 0, 195),
    ("large-tom-under21",      "Tom",       110, 0, 225),

    ("chh9",                   "CHat2",      90, 1, 150),
    ("chh10",                  "CHat3",      90, 1, 150),
    ("fhh7",                   "FootHat",    86, 1, 145),
    ("metal-stick2",           "Metal",      92, 0, 175),

    ("rimshot-alt2",           "Rim2",      100, 0, 190),
    ("rimshot-alt3",           "Rim3",      100, 0, 190),
    ("crash22",                "Crash",     104, 0, 190),
    ("crash-edge2",            "CrashEdge",  98, 0, 180),
]


def load_f32(stem):
    with open(f"{stem}.f32", "rb") as fh:
        raw = fh.read()
    return list(struct.unpack("<%df" % (len(raw) // 4), raw))


def condition(s):
    """DC-remove, trim, cap, fade, normalize. Returns (samples, was_truncated)."""
    if not s:
        return [], False
    dc = sum(s) / len(s)
    s = [v - dc for v in s]

    peak = max(abs(v) for v in s) or 1e-9
    thr = peak * SILENCE_FLOOR
    start = 0
    for i, v in enumerate(s):
        if abs(v) > thr:
            start = i
            break
    # Back off a hair so the transient's very first rise is not clipped off.
    start = max(0, start - int(RATE * 0.0005))
    end = len(s)
    for i in range(len(s) - 1, start, -1):
        if abs(s[i]) > thr:
            end = min(len(s), i + int(RATE * 0.01))
            break
    s = s[start:end]

    truncated = len(s) > MAX_FRAMES
    if truncated:
        s = s[:MAX_FRAMES]

    n_in = max(1, int(RATE * FADE_IN_MS / 1000))
    for i in range(min(n_in, len(s))):
        s[i] *= i / n_in
    out_ms = FADE_OUT_TRUNCATED_MS if truncated else FADE_OUT_NATURAL_MS
    n_out = max(1, int(RATE * out_ms / 1000))
    for i in range(min(n_out, len(s))):
        idx = len(s) - 1 - i
        s[idx] *= i / n_out

    peak = max(abs(v) for v in s) or 1e-9
    g = TARGET_PEAK / peak
    return [v * g for v in s], truncated


def to_i16(s):
    out = []
    for v in s:
        q = int(round(v * 32767.0))
        out.append(max(-32768, min(32767, q)))
    return out


def write_wav(path, samples):
    data = struct.pack("<%dh" % len(samples), *samples)
    with open(path, "wb") as fh:
        fh.write(b"RIFF")
        fh.write(struct.pack("<I", 36 + len(data)))
        fh.write(b"WAVEfmt ")
        fh.write(struct.pack("<IHHIIHH", 16, 1, 1, RATE, RATE * 2, 2, 16))
        fh.write(b"data")
        fh.write(struct.pack("<I", len(data)))
        fh.write(data)


os.makedirs("out_wav", exist_ok=True)
rows, total = [], 0
print(f"{'pad':>3} {'label':<10}{'src':<26}{'frames':>7}{'sec':>6}{'KB':>6}{'trunc':>7}")
for i, (stem, label, vel, choke, gain) in enumerate(KIT):
    s, trunc = condition(load_f32(stem))
    q = to_i16(s)
    kb = len(q) * 2 / 1024
    total += len(q) * 2
    write_wav(f"out_wav/pad{i+1:02d}.wav", q)
    rows.append((i, stem, label, vel, choke, gain, q))
    print(f"{i+1:>3} {label:<10}{stem:<26}{len(q):>7}{len(q)/RATE:>6.2f}{kb:>6.1f}"
          f"{('yes' if trunc else '-'):>7}")
print(f"\ntotal PCM: {total/1024:.1f} KB ({total/1024/1024:.2f} MB)")

# --- C source -------------------------------------------------------------
with open("KitSamples.cpp", "w") as fh:
    fh.write('#include "KitSamples.h"\n\n')
    fh.write("// GENERATED by scripts/build-builtin-kit.py - do not hand-edit.\n")
    fh.write("// Source: a real acoustic kit recorded at 96 kHz/24-bit, decoded to\n")
    fh.write("// mono, resampled to the engine rate, DC-removed, trimmed, faded, and\n")
    fh.write("// peak-normalized to -1 dBFS in float before int16 quantization. Per-pad\n")
    fh.write("// balance is restored by the gain column, not by the sample levels.\n\n")
    for i, stem, label, vel, choke, gain, q in rows:
        fh.write(f"// pad {i+1}: {label} <- {stem}.wav ({len(q)} frames)\n")
        fh.write(f"static const int16_t kPad{i:02d}[] = {{\n")
        for j in range(0, len(q), 16):
            fh.write("  " + ",".join(str(v) for v in q[j:j + 16]) + ",\n")
        fh.write("};\n\n")
    fh.write("const KitSample kBuiltinKit[kBuiltinKitPads] = {\n")
    for i, stem, label, vel, choke, gain, q in rows:
        fh.write(f'  {{kPad{i:02d}, {len(q)}, {RATE}, "{label}", "kit:{stem}", '
                 f"{vel}, {choke}, {gain}}},\n")
    fh.write("};\n")

with open("KitSamples.h", "w") as fh:
    fh.write("""#ifndef CYPHER_TUNE_KIT_SAMPLES_H
#define CYPHER_TUNE_KIT_SAMPLES_H

#include <Arduino.h>

// The built-in kit, baked into flash as 16-bit PCM at the engine rate.
// Generated from real drum recordings by scripts/build-builtin-kit.py.
//
// These live in flash (.rodata, memory-mapped) but are COPIED into PSRAM at
// boot rather than played in place: an NVS write (theme/brightness) briefly
// disables the flash cache, and the audio task reading XIP-mapped sample data
// at that moment would glitch or fault. PSRAM costs ~480 KB of 32 MB.
struct KitSample {
  const int16_t *pcm;
  uint32_t frames;
  uint32_t rate;
  const char *label;
  const char *ref;
  uint8_t defaultVelocity;
  uint8_t chokeGroup;
  uint8_t gain;
};

static const uint8_t kBuiltinKitPads = 16;
extern const KitSample kBuiltinKit[kBuiltinKitPads];

#endif
""")
print("wrote KitSamples.cpp / KitSamples.h / out_wav/pad01..16.wav")
