#!/usr/bin/env python3
"""Validate the Cypher Flock signature catalog and generate its Arduino header."""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
CATALOG = ROOT / "signatures/cypher-flock/catalog.json"
HEADER = ROOT / "shared/FlockSignatureCatalog/src/FlockSignatureCatalog.h"


def fail(message: str) -> None:
    raise ValueError(message)


def load_catalog() -> tuple[dict, str]:
    raw = CATALOG.read_text(encoding="utf-8")
    data = json.loads(raw)
    if data.get("schema") != 1 or not data.get("version"):
        fail("catalog requires schema=1 and a version")
    return data, raw


def validate(data: dict) -> None:
    mac_re = re.compile(r"^[0-9a-f]{2}(?::[0-9a-f]{2}){2}$")
    uuid_re = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")
    ids: set[str] = set()
    values: set[str] = set()
    required_rule_fields = {"id", "family", "pattern", "evidence", "source", "source_commit",
                            "verified", "false_positive_risk", "alert_eligible", "rejection_reason"}
    for rule in data.get("rules", []):
        missing = required_rule_fields - set(rule)
        if missing:
            fail(f"catalog rule {rule.get('id', '<unknown>')} missing {sorted(missing)}")
    for item in data["wifi_ouis"]:
        if not mac_re.fullmatch(item["value"]):
            fail(f"invalid OUI: {item['value']}")
        if item["id"] in ids or item["value"] in values:
            fail(f"duplicate enabled signature: {item}")
        if item["evidence"] not in {"high", "medium", "candidate"}:
            fail(f"invalid evidence tier: {item['evidence']}")
        ids.add(item["id"])
        values.add(item["value"])
    rejected = {item["value"] for item in data["rejected"] if item["type"] == "wifi_oui"}
    overlap = values & rejected
    if overlap:
        fail(f"enabled/rejected OUI conflict: {sorted(overlap)}")
    for group in ("raven_custom_uuids", "raven_context_uuids"):
        for item in data[group]:
            if not uuid_re.fullmatch(item["value"]):
                fail(f"invalid UUID: {item['value']}")


def tier(value: str) -> int:
    return {"candidate": 1, "medium": 2, "high": 3}[value]


def generate(data: dict, raw: str) -> str:
    digest = hashlib.sha256(raw.encode("utf-8")).hexdigest()[:12]
    lines = [
        "// Generated by scripts/generate-flock-catalog.py. Do not edit.",
        "#ifndef CYPHER_FLOCK_SIGNATURE_CATALOG_H",
        "#define CYPHER_FLOCK_SIGNATURE_CATALOG_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "namespace FlockCatalog {",
        f'static const char VERSION[] = "{data["version"]}";',
        f'static const char HASH[] = "{digest}";',
        "enum EvidenceTier : uint8_t { kCandidate = 1, kMedium = 2, kHigh = 3 };",
        "struct OuiSignature { const char *id; uint8_t bytes[3]; EvidenceTier evidence; bool standalone; };",
        "struct NameSignature { const char *id; const char *value; bool prefix; EvidenceTier evidence; };",
        "struct ManufacturerSignature { const char *id; uint16_t value; EvidenceTier evidence; bool standalone; };",
        "struct UuidSignature { const char *id; const char *value; };",
        "",
        "static const OuiSignature WIFI_OUIS[] = {",
    ]
    for item in data["wifi_ouis"]:
        if not item.get("enabled", True):
            continue
        parts = [int(part, 16) for part in item["value"].split(":")]
        lines.append(
            f'  {{"{item["id"]}", {{0x{parts[0]:02x}, 0x{parts[1]:02x}, 0x{parts[2]:02x}}}, '
            f'(EvidenceTier){tier(item["evidence"])}, {str(bool(item["standalone"])).lower()}}},'
        )
    lines += [
        "};",
        "static const size_t WIFI_OUI_COUNT = sizeof(WIFI_OUIS) / sizeof(WIFI_OUIS[0]);",
        "",
        "static const NameSignature BLE_NAMES[] = {",
    ]
    for item in data["ble_names"]:
        if item.get("enabled", True):
            lines.append(
                f'  {{"{item["id"]}", "{item["value"]}", '
                f'{str(item["match"] == "prefix").lower()}, (EvidenceTier){tier(item["evidence"])}}},'
            )
    lines += [
        "};",
        "static const size_t BLE_NAME_COUNT = sizeof(BLE_NAMES) / sizeof(BLE_NAMES[0]);",
        "",
        "static const ManufacturerSignature BLE_MANUFACTURERS[] = {",
    ]
    for item in data["ble_manufacturers"]:
        if item.get("enabled", True):
            lines.append(
                f'  {{"{item["id"]}", {item["value"]}, (EvidenceTier){tier(item["evidence"])}, '
                f'{str(bool(item["standalone"])).lower()}}},'
            )
    lines += [
        "};",
        "static const size_t BLE_MANUFACTURER_COUNT = sizeof(BLE_MANUFACTURERS) / sizeof(BLE_MANUFACTURERS[0]);",
        "",
        "static const UuidSignature RAVEN_CUSTOM_UUIDS[] = {",
    ]
    for item in data["raven_custom_uuids"]:
        lines.append(f'  {{"{item["id"]}", "{item["value"]}"}},')
    lines += [
        "};",
        "static const size_t RAVEN_CUSTOM_UUID_COUNT = sizeof(RAVEN_CUSTOM_UUIDS) / sizeof(RAVEN_CUSTOM_UUIDS[0]);",
        "",
        "static const UuidSignature RAVEN_CONTEXT_UUIDS[] = {",
    ]
    for item in data["raven_context_uuids"]:
        lines.append(f'  {{"{item["id"]}", "{item["value"]}"}},')
    lines += [
        "};",
        "static const size_t RAVEN_CONTEXT_UUID_COUNT = sizeof(RAVEN_CONTEXT_UUIDS) / sizeof(RAVEN_CONTEXT_UUIDS[0]);",
        "}  // namespace FlockCatalog",
        "",
        "#endif",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the generated header differs")
    args = parser.parse_args()
    data, raw = load_catalog()
    validate(data)
    generated = generate(data, raw)
    if args.check:
        if not HEADER.exists() or HEADER.read_text(encoding="utf-8") != generated:
            print(f"stale generated catalog: {HEADER}", file=sys.stderr)
            return 1
        print(f"catalog OK version={data['version']} entries={len(data['wifi_ouis'])}")
        return 0
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(generated, encoding="utf-8")
    print(f"generated {HEADER.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"catalog error: {exc}", file=sys.stderr)
        raise SystemExit(1)
